deploy:
  provider: pypi
  user: nightexcessive
  password:
    secure: FOums9R8tT7ASMIz1PLfiHFWYsPqOxJ0mm4DQaD6tfIJheW3isIWxVg0s1SC+r9iGGGMvhYVkY+OPA+i+YxsQIixdetnCZ1XtUS28XZhJYTBY1HIl5KpV2j8qDfI3CHOsv4wgbMDav/3F/cZEDf6Vn6hzKmfAeBMAddDk+bBmAfCr/unybfN+JAjDEd4ixEe5LM8ppUSr62XemFGNSnOw1QHlKa2Tq8udCQf+zmgdyys8Po0QT4wb/OB5oevddF6jwuqPw8i22RQyHDU+Q8ApsjU14m9KFMAPiwBx8+Uh9dkpVk+sGYJ6epFmLQcBkAwgee5T0sn0GHVQX5BwHI8jk0TPzEBANHHGIoHdU87OZ0rwJuj/fA86t7OPFgwp1iQ0ElxRHYvAI67e15IEZujDLZgV5BOFmXASMQck5t8K4CXCTEui9puUL3Pv7U53avdlXMPkrXlJN2sENfWXUzXjhLhnEagrOuUTiZGdwYc35C4Knh4iQbvRdN85FtqZVWvnEkSC94S4G5HWcds18djpm8JtKcSketgaBalrmOOjurcbA9JUGzZhCsU4RiOsKD6hDkQ/r4eDM/p59yXavWBKKXncqLeueyGmzdWMwb+J8P9zuDZDSGkPnwiJ/T/lW3xWwtqaKw2u3COmzgtIWJJZAsrfFjyw2e9LIwpZWrFdp4=
  distributions: sdist bdist_wheel
  on:
    tags: true

install: pip install -U tox-travis coveralls
language: python
python:
- 3.6
- 3.5
- 3.4
- 3.3
- 2.7
script: tox
after_success:
    - coveralls
