deploy:
  provider: pypi
  user: nightexcessive
  password:
    secure: XRedXapWu6mBkou3f2ODqua38UbBPuJ39jucQ0gaLcdNerr2Y+0SCWfCL9ghl5dmzXPKBZXsymVlVcr+5yJ60AlTBBaLiB+BadMhvl7qL0FfrWRgageMgW4K+fRaVL+V+gBGXJtUQ4Z2F749l+ZMptehisvlPq6vw0y6RxySQcx4xN1cCKlNHJwIQBnRHx2G9Z9ocBPjtFTbWOT7bhKP93eJDgfa+b5uzVgH114eOO9mIkhoCq5Z2fDvBeA1aNUa89C+iRWV17oWCYGDR5pfSG+0wyLyFU5zNT0qAWmrPMAR3YDjA1h1w/PKgwCJ6QUUI1PvvzPxzsXX9OkhCGnzIRx08H9DJXVAVatVODfM5uHunlCuCrGR5lNd1VinA4z0L5t3EJYFZZrAUVHk4VCDsVuPgkRcA7LiUuGuoog86qSU2ntTOCPgKCpzcH32ephJlXoHDoxGYJvnPQmVrW8FjZEX6xqrxHemIgMXEKclBkuepVoFsEOhRRpvm3PaLN0xnhzb2TSPhWUfSrsk2iO+u4v+FAooQQTayslzlgKDUZailGLxIxLgvY1UtWQoJ1g3GJ8DYewx8j67IXqWuf2+2GkwtWEi/1HUXoFpFbKXmhNt0Jdp/f5dUXWu2qRZWXopw8/STG6BWiHOftBW6YEBLiiKRrG8DbY0WF+1o6G/AXw=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: '3.6'

install: pip install -U tox-travis coveralls
language: python
python:
- 3.6
- 3.5
- 3.4
- 3.3
- 2.7
script: tox
after_success:
    - coveralls
